school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studentportal/', include('studentportal.urls')),
    path("accounts/", include("django.contrib.auth.urls"))
]

studentportal/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.redirect_to_login),
    path('s/', views.redirect_to_login),
    path('s/<slug:username>/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='user_login')
]

studentportal/models.py
from django.db import models
from . import SUBJECT_CHOICES, SUBJECT_TYPE_CHOICES, CLASS_CHOICES, REPORT_COLUMNS
from .utils import assign_grade

class Student(models.Model):
    """Consists of the parameters and methods performed on a student"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length=150, blank=True, unique=True)
    full_name = models.CharField(max_length=201, blank=True)
    age = models.PositiveIntegerField()
    class_name = models.CharField(max_length=10, choices=CLASS_CHOICES)
    password = models.CharField(max_length=128)

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
        if not self.username:
            self.username = f"{self.id}-{self.first_name.lower()}-{self.last_name.lower()}"
            self.full_name = f"{self.last_name} {self.first_name}"
        super().save(*args, **kwargs)

    def compile_scores(self):
        """Compile student scores"""
        scores = {'data': {}}
        scores['columns'] = []
        for exam_code, exam_type in SUBJECT_TYPE_CHOICES:
            temp_dict = {}
            temp_total = 0
            subject_count = 0
            for subject in self.subject_set.all(): # self.subject_set.all() returns all subjects that are related to this username
                if subject.type != exam_code:
                    continue
                if subject.name in REPORT_COLUMNS:
                    temp_dict[subject.name] = subject.score
                    temp_total += subject.score
                    subject_count += 1
            # GRADE
            if subject_count > 0:
                avg = temp_total / subject_count
            else:
                avg = 0
            grade = assign_grade(avg)

            temp_dict['TOTAL'] = temp_total
            temp_dict['AVG'] = avg
            temp_dict['GRADE'] = grade

            scores['data'][exam_code] = {}
            for k, v in temp_dict.items():
                if k in REPORT_COLUMNS:
                    scores['data'][exam_code][k] = v
                    scores['columns'].append(k)
        # Remove duplicates from columns while maintaining order
        seen = set()
        unique_columns = []
        for col in scores['columns']:
            if col not in seen:
                unique_columns.append(col)
                seen.add(col)
        scores['columns'] = unique_columns
        return scores

    def __str__(self):
        return f"{self.id}-{self.first_name}-{self.last_name}"


class Subject(models.Model):
    name = models.CharField(max_length=10, choices=SUBJECT_CHOICES)
    score = models.PositiveBigIntegerField()
    type = models.CharField(max_length=10, choices=SUBJECT_TYPE_CHOICES)
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE) # Many-to-one relationships

    def __str__(self):
        return f"{self.student_id.id}-{self.name}-{self.score}".replace(" ", "-")

studentportal/forms.py
from django import forms
from .models import Student

class LoginForm(forms.Form):
    username = forms.CharField(label="User ID", help_text="e.g 1-joshua-kalule")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Student
        fields = ["first_name", "last_name", "age", "class_name", "password"]

studentportal/views.py
from pprint import pprint
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models
from .forms import SignUpForm, LoginForm
from .utils import compile_score_table

# Create your views here.


def redirect_to_login(request):
    return redirect('user_login')

def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
        student = models.Student.objects.filter(username=username).first()
        if student:
            if student.password == password:
                return redirect('home', username=username)

        form = LoginForm(initial={'username': username})
        errors = ["Invalid username or password"]
        return render(request, "login.html",  {"form": form, "errors": errors})
    else:
        form = LoginForm()
    context = {
        "form": form
    }
    return render(request, "login.html",  context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            # process the data here
            student = form.save(commit=False)
            username = student.username
            if models.Student.objects.filter(username=username):
                errors = ["A user with those names already exists"]
                form = SignUpForm(initial={'class_name': 'S1'})
                return render(request, "signup.html", {"form": form, "errors": errors})

            form.save()
            return redirect('home', username=username)
    else:
        form = SignUpForm(initial={'class_name': 'S1'})
    context = {
        "form": form
    }
    return render(request, "signup.html", context)


def home(request, username):
    student = models.Student.objects.filter(username=username).first()
    if not student:
        return redirect('user_login')
    pprint(student.compile_scores())
    pprint(compile_score_table(student.compile_scores()))
    scores_header, scores_data = compile_score_table(student.compile_scores())
    context = {
        "student": student,
        "scores_header": scores_header,
        "scores_data": scores_data
    }
    return render(request, 'home.html', context)

studentportal/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous" />

    <title>
      {% block title %}
        Title
      {% endblock %}
    </title>
  </head>
  <body>
    <div class="container pt-3">
      {% block navbar %}
      {% endblock %}
      {% block body %}
        Body goes here
      {% endblock %}
      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
         -->
    </div>
  </body>
</html>

studentportal/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Home
{% endblock %}

{% block navbar %}
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' student.username %}">
        <img src="{% static 'images/school-portal-blue.svg' %}" alt="School Project Brand" width="60" height="60" class="d-inline-block align-text-top" />
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_login' %}">Sign out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block body %}
  <div class="row mt-5">
    <div class="col-auto">
      <h2>Welcome {{ student.full_name }}</h2>
    </div>
    <div class="col-auto ms-auto">
      <div class="btn-group" role="group" aria-label="Class and age">
        <button type="button" class="btn btn-outline-secondary">{{ student.get_class_name_display }}</button>
        <button type="button" class="btn btn-outline-secondary">{{ student.age }} years</button>
      </div>
    </div>
  </div>
  <div class="row mt-3">
    <nav class="nav nav-tabs flex-column flex-sm-row">
      <a class="flex-sm-fill text-sm-center nav-link active" aria-current="page" href="#"><strong>Report</strong></a>
      <a class="flex-sm-fill text-sm-center nav-link" href="#">Details</a>
    </nav>
  </div>
  <div class="row mt-3">
    <table class="table">
      <thead>
        <tr>
          {% for header in scores_header %}
            <th scope="col">{{ header }}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for row in scores_data %}
          <tr>
            {% for column in row %}
              {% if forloop.first %}
                <th scope="row">{{ column }}</th>
              {% else %}
                <td>{{ column|default:'-' }}</td>
              {% endif %}
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

studentportal/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
  Login
{% endblock %}
{% block body %}
  <div class="container px-5">
    <div class="row justify-content-center">
      <div class="col-auto">
        <img src="{% static 'images/school-portal-blue.png' %}" alt="School Portal Banner" class="rounded my-4" style="width: 250px;" />
      </div>
    </div>
    {% if errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in errors %}
          {{ error }}
          <br\>
        {% endfor %}
      </div>
    {% endif %}
    <form class="row g-3" method="post">
      {% csrf_token %}
      <div class="col-12">
        <label for="{{ form.username.id_for_label }}" class="form-label">{{ form.username.label }}</label>
        {% render_field form.username|add_class:'form-control' %}
        {{ form.username.errors }}
      </div>
      <div class="col-12">
        <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}</label>
        {% render_field form.password|add_class:'form-control' %}
        {{ form.password.errors }}
      </div>
      <div class="col-12 d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
      <div class="col-12 d-flex justify-content-center">
        <a href="{% url 'signup' %}">Create account</a>
      </div>
    </form>
  </div>
{% endblock %}

studentportal/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
  SignUp
{% endblock %}
{% block body %}
  <div class="container px-5">
    <div class="row justify-content-center">
      <div class="col-auto">
        <img src="{% static 'images/school-portal-blue.png' %}" alt="School Portal Banner" class="rounded my-4" style="width: 250px;" />
      </div>
    </div>
    {% if errors %}
      <div class="alert alert-danger" role="alert">
      {% for error in errors %}
        <p style="color: red;">{{ error }}</p>
      {% endfor %}
      </div>
    {% endif %}
    <form class="row g-3" method="post">
      {% csrf_token %}
      <div class="col-md-6">
        <label for="{{ form.first_name.id_for_label }}" class="form-label">{{ form.first_name.label }}</label>
        {% render_field form.first_name|add_class:'form-control' %}
        {{ form.first_name.errors }}
      </div>
      <div class="col-md-6">
        <label for="{{ form.last_name.id_for_label }}" class="form-label">{{ form.last_name.label }}</label>
        {% render_field form.last_name|add_class:'form-control' %}
        {{ form.last_name.errors }}
      </div>
      <div class="col-12">
        <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}</label>
        {% render_field form.password|add_class:'form-control' %}
        {{ form.password.errors }}
      </div>
      <div class="col-6">
        <label for="{{ form.age.id_for_label }}" class="form-label">{{ form.age.label }}</label>
        {% render_field form.age|add_class:'form-control' %}
        {{ form.age.errors }}
      </div>
      <div class="col-6">
        <label for="{{ form.class_name.id_for_label }}" class="form-label">{{ form.class_name.label }}</label>
        {% render_field form.class_name|add_class:'form-control' %}
        {{ form.class_name.errors }}
      </div>
      <div class="col-12 d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">Sign in</button>
      </div>
      <div class="col-12 d-flex justify-content-center">
        <a href="{% url 'user_login' %}">Already have an account?</a>
      </div>
    </form>
  </div>
{% endblock %}